language: objective-c
osx_image: xcode7.1
before_install:
  - gem install cocoapods -v '0.38.2'
script:
  - xcodebuild test -workspace TIBCO\ JasperMobile.xcworkspace -scheme TIBCO\ JasperMobile\ Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES 
